### ISSUE TITLE
Language Module Integration

### ISSUE THREAD

**Issue by NukeMaster0** [kakaroto/fvtt-module-polyglot#28] opened 2020-07-27 20:49 UTC
A module known as "Obsidian" or https://bitbucket.org/Fyorl/obsidian/src/master/ could work wonders as using both Obsidian and Polyglot just doesn't work, this is because Obsidian is using a different character sheet then the default and well it would be nice if Polyglot could recognize Obsidian's sheet, so maybe a support?

Yeah, I couldn't figure out the pull request if this is where it goes.

**Comment by kakaroto** [comment] 2020-07-27 22:12
Sorry, I won't support obsidian.
While I love what Fyorl did with obsidian and it looks gorgeous, the problem is that I think obsidian is modifying the system's data and using its own custom data format. That's a very dangerous thing to do because it means if you disable the module, then your actor becomes broken and you loose your content, and you can't use a different sheet with the actor anymore. Regardless, the actor data format is defined by the system, not but a module. I know that Fyorl was told he shouldn't do this and I don't know if he has plans to migrate his data to match the dnd5e system's template, but until he does, it won't work, and polyglot will certainly not be the only module that will be incompatible with obsidian and forcing everyone to add special cases for any module that doesn't do things correctly is not a viable long term, or scalable solution.

This is my assumption on information known to me for a while which may be outdated, so if I'm mistaken, feel free to correct me.

**Closed by kakaroto** 2020-07-27 22:12 UTC

**Comment by NukeMaster0** [comment] 2020-07-28 00:37
> Sorry, I won't support obsidian.
> While I love what Fyorl did with obsidian and it looks gorgeous, the problem is that I think obsidian is modifying the system's data and using its own custom data format. That's a very dangerous thing to do because it means if you disable the module, then your actor becomes broken and you loose your content, and you can't use a different sheet with the actor anymore. Regardless, the actor data format is defined by the system, not but a module. I know that Fyorl was told he shouldn't do this and I don't know if he has plans to migrate his data to match the dnd5e system's template, but until he does, it won't work, and polyglot will certainly not be the only module that will be incompatible with obsidian and forcing everyone to add special cases for any module that doesn't do things correctly is not a viable long term, or scalable solution.
> 
> This is my assumption on information known to me for a while which may be outdated, so if I'm mistaken, feel free to correct me.

Darn, well I hope he changes his mind then, thanks!
